### PR TITLE
Add Today link to contest calendar view; #724

### LINKED ISSUE #724: Contest calendar should show today
Instead of just previous and next months, we should also show today, so we can easily get back to the current month:

default

### PR DESCRIPTION
**Pull request by TheAvidDev**
Fixed #724

### CODE REVIEW

**Comment by Xyene** [comment]
The code looks good, thanks. What does this look like in a screenshot?

**Comment by TheAvidDev** [comment]
What it looks like on the current month:
today

What it looks like when you are at min_month (no context prior):
today_next
This works with the max_month too.

What it looks like before current month but after an earlier contest.
today_all

**Comment by TheAvidDev** [comment]
Accidentally closed.

**Comment by Xyene** [comment]
Looks good, thanks!

**Pull request merged**
